import type { Metadata } from "next";
import { Oswald, Work_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { classNames } from "@/lib/utils/classNames";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

export const work_sans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

export const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv" className="scroll-smooth">
      <body
        className={classNames(
          oswald.variable,
          work_sans.variable,
          poppins.variable
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
